### ISSUE TITLE
NodeStudy: 第四天任务

### ISSUE THREAD

**Issue by imsobear** [ynliSonia/nodeStudy#4]
## 任务：
- 了解 RESTful
- 将昨天的应用改成 RESTful 的风格
- 完成 delete 的功能
- **重点**：对自己的代码风格，命名规范，注释等再多注意一些
## 推荐阅读：
- [理解RESTful架构](http://www.ruanyifeng.com/blog/2011/09/restful.html)
- [REST](http://zh.wikipedia.org/wiki/REST)
- [Airbnb JavaScript Style Guide() ](https://github.com/airbnb/javascript)
- [Code Guide by @mdo](http://codeguide.co/#html), 有对应的中文版
## 备注：
- 以后的总结就放在 issue 里，方便讨论
- 对于代码风格，重点是要在自己的代码里实践，仅仅是阅读一下没有意义

**Comment by ynliSonia** [comment]
## 总结
- 关于restful，删除功能尝试引入了rest，但是总体理解还很浅显，阅读了另外关于rest的文章，觉得还不错；
- 代码风格，待改善。

## 阅读文章
- http://www.cnblogs.com/artech/p/restful-web-api-02.html  [rest]

**Comment by imsobear** [comment]
@ynliSonia 

OK

and, markdown 里链接的正确写法是 `[xxx](http://xxxx)`
